### ISSUE TITLE
Add ConditionalOrders Service

### ISSUE THREAD

**Issue by atakanyenel** [grpcoin/grpcoin#4]
Instead of buying/selling at current price, users should be able to CRUD a conditional trade order, that can also execute when they are away.

The semantics can be like following:

Service ConditionalOrders
   - CreateConditionalOrder (returns id)
   - ListConditionalOrders (that only belong to user)
   - DeleteConditionalOrder (takes id)
   - CheckOrders(only called from server)

The **Condition** will be the price of the crypto and the amount will be the asset you are giving(checked with a oneof field). For example:

```
$ ./client conditional create buy btc 37000 50k
will buy 50k worth of bitcoin when its price is equal/below 37000.
```
```
$ ./client conditional create sell btc 38000 1
will sell 1 btc when the price hits 38000. 
```

To prevent over-subscription, as soon as the conditional order is placed, the resources will be taken from the user's account and preserved in the new table, tied to the order. Cancelling a pending order will return the unit back to user's bank.

Every time the ticker updates the current price, it will send an rpc to CheckOrders, which will search for orders that satisfy the new price, and execute them. (If every time is too much, a different frequency can be used).

Orders will always execute with the price in their contract and not from the current price. E.g. if you give sell order at 38k, but the new price was 40k in the next ticker update, it will still sell from 38. Tough luck...

For the leaderboard, the assets that are tied to a conditional order will also be taken into account while calculating the final worth.

Since this is a learning game , a different metric can show the total asset value tied to pending conditional orders that the exchange has at any time, which will teach traders who the actual winner is :)

**Comment by ahmetb** [comment]
Cloud Run can't run things in the background so probably wontfix for now. Clients can implement this using the API.

**Comment by atakanyenel** [comment]
Yes, clients can implement this for sure.

But which part of this is a background job ? Are you referring to the time, when there is no traffic to the server so it turns off ?

Otherwise this is a running service that watches the ticker endpoint in a goroutine and sends some rpcs to trade service.

**Comment by ahmetb** [comment]
> But which part of this is a background job ? Are you referring to the time, when there is no traffic to the server so it turns off ?

Yes. Executing the conditional order, as I understand it, requires a trigger listening on the prices, which we'd need to do run in the background outside the context of any requests.
